# packstack demo automation
# jamie duncan <jduncan@redhat.com>

- name: copy over the atomic image to the controller node
  copy: src={{ atomic_image_qcow }} dest={{ atomic_image_qcow_dest }}
  when: role == 'controller'

- name: copy over the swift demo image
  copy: src={{ swift_demo_image_sourcedir}}/{{ swift_demo_image }} dest={{ swift_demo_image_destdir}}/{{ swift_demo_image }}
  when: role == 'controller'

- name: add the atomic image to glance
  shell: source {{ rc_file }} && glance image-create --disk-format qcow2 --container-format bare --name {{ atomic_image_name }} --file {{ atomic_image_qcow_dest }}
  args:
    executable: /bin/bash
  when: role == 'controller'

- name: create a swift container
  shell: source {{ rc_file }} && swift post {{ swift_container }}
  args:
    executable: /bin/bash
  when: role == 'controller'

- name: upload a demo image
  shell: source {{ rc_file }} && swift upload {{ swift_container }} {{ swift_demo_image_destdir}}/{{ swift_demo_image }}
  args:
    executable: /bin/bash
  when: role == 'controller'
