- name: clean up any old temporary workspaces
  file: name={{ tmp_workspace }} state=absent
  ignore_errors: true

- name: power down any old instances of this group
  virt: name={{ hostvars[item]['inventory_hostname'] }}
        command=destroy
        uri=qemu:///system
  ignore_errors: true
  with_items: "{{ groups[group] }}"

- name: undefine any old instances of this group
  virt: name={{ hostvars[item]['inventory_hostname'] }}
        command=undefine
        uri=qemu:///system
  ignore_errors: true
  with_items: "{{ groups[group] }}"

- name: clean up any old disk images
  file: name={{ kvm_disk_dir }}/{{ hostvars[item]['inventory_hostname'] }}.qcow2 state=absent
  with_items: "{{ groups[group] }}"
  ignore_errors: true

- name: clean up any cloud-init ISOs
  file: name={{ kvm_disk_dir }}/{{ hostvars[item]['inventory_hostname'] }}-ci.iso state=absent
  with_items: "{{ groups[group] }}"
  ignore_errors: true

- name: clean up any old data disk images
  file: name={{ kvm_disk_dir }}/{{ hostvars[item]['inventory_hostname'] }}-data.qcow2 state=absent
  with_items: "{{ groups[group] }}"
  ignore_errors: true

- name: remove any stale entries for these virtual Machines by hostname
  shell: "ssh-keygen -R {{ hostvars[item]['inventory_hostname'] }} -f {{ ssh_known_hosts_file}}"
  with_items: "{{ groups[group] }}"

- name: remove any stale entries for these virtual Machines by ip
  shell: "ssh-keygen -R {{ hostvars[item]['ip'] }} -f {{ ssh_known_hosts_file}}"
  with_items: "{{ groups[group] }}"

- name: collect the current username
  local_action: command whoami
  sudo: no
  register: local_username

- name: set the proper permissions back on known_hosts
  file: path={{ ssh_known_hosts_file }}
        owner={{ local_username.stdout }}
        group={{ local_username.stdout }}
        mode=0600
