# common tasks for all rhel systems

- name: Register System with RHN Subscription Manager
  redhat_subscription: state=present
                       username={{ rhn_user }}
                       password={{ rhn_pass }}
  when: ansible_distribution == 'RedHat'

- name: attach a valid subscription
  command: subscription-manager attach --pool={{ sub_poolid }}
  when: ansible_distribution == 'RedHat'
