etc_hosts: "{{ lookup('file', '/etc/hosts') }}"
tmp_workspace: /tmp/ansible-tmp

# networking parameters
libvirt_network: default
network: 192.168.122.0
netmask: 255.255.255.0
gateway: 192.168.122.1

ssh_known_hosts_command: "ssh-keyscan -H -T 10"
