# Prepares a system to be a hypervsior and sets up the hosts group 'guests' as kvm guests
# Jamie Duncan

#- name: ensure kvm is installed and started
#  service: name=libvirtd state=started enabled=yes
#  register: libvirtd

#- name: wait for libvirtd to start up
#  pause: seconds=30
#  when: libvirtd.changed

#- name: ensure genisoimage is installed
#  yum: name=genisoimage state=latest

- name: collect dns server information
  shell: grep -m 1 nameserver /etc/resolv.conf | awk '{ print $2}'
  register: dns

- name: clean up any old temporary workspaces
  file: name={{ tmp_workspace }} state=absent
  ignore_errors: true

- name: create workspace folder
  file: name={{ tmp_workspace }} state=directory

- name: add ssh public key to hypervisor for hosts
  copy: src={{ ssh_key }} dest={{ tmp_workspace }}/ssh_key.pub

- name: create hosts file for hypervisor
  template: src=../templates/hosts dest=/etc/hosts

- include: packstack_guests.yml
  when: deploy_packstack

- include: rhevh_guest.yml
  when: deploy_rhevm

- include: rhevm_guest.yml
  when: deploy_rhevm

- include: atomic_guest.yml
  when: deploy_atomic

- name: collect the current username
  local_action: command whoami
  sudo: no
  register: local_username

- name: set the proper permissions back on known_hosts
  file: path={{ ssh_known_hosts_file }}
        owner={{ local_username.stdout }}
        group={{ local_username.stdout }}
        mode=0600
