sub_poolid: 8a85f98152a5bd100152a8229dcd3833
atomic_disk_image: "{{ lookup('env','HOME') }}/Projects/atomic/vms/rhel/rhel-atomic-cloud-7.2-12.x86_64.qcow2"
rhel_disk_image: "{{ lookup('env','HOME') }}/Downloads/rhel-guest-image-7.2-20160302.0.x86_64.qcow2"
cfme_disk_image: "{{ lookup('env','HOME') }}/Downloads/cfme-rhos-5.5.4.2-1.x86_64.qcow2"
kvm_disk_dir: "{{ lookup('env','HOME') }}/Projects/libvirt-store"
ssh_key: "{{ lookup('env','HOME') }}/.ssh/id_rsa"
ssh_known_hosts_file: "{{ lookup('env','HOME') }}/.ssh/known_hosts"

etc_hosts: "{{ lookup('file', '/etc/hosts') }}"
tmp_workspace: /tmp/ansible-tmp

ssh_known_hosts_command: "ssh-keyscan -H -T 10"

# libvirt networking parameters
libvirt_network: default
network: 192.168.122.0
netmask: 255.255.255.0
gateway: 192.168.122.1
