# Prepares a system to be a hypervsior and sets up the hosts group 'guests' as kvm guests
# Jamie Duncan

- name: ensure kvm is installed and started
  service: name=libvirtd state=started enabled=yes
  register: libvirtd

- name: wait for libvirtd to start up
  pause: seconds=30
  when: libvirtd.changed

- name: ensure genisoimage is installed
  yum: name=genisoimage state=latest

- name: collect dns server information
  shell: grep -m 1 nameserver /etc/resolv.conf | awk '{ print $2}'
  register: dns

- name: clean up any old temporary workspaces
  file: name={{ tmp_workspace }} state=absent
  ignore_errors: true

- name: create workspace folder
  file: name={{ tmp_workspace }} state=directory

- name: add ssh public key to hypervisor for hosts
  copy: src={{ ssh_key }} dest={{ tmp_workspace }}/ssh_key.pub

- name: create hosts file for hypervisor
  template: src=../templates/hosts dest=/etc/hosts

- name: remove any old guest instances
  virt: name={{ hostvars[item]['inventory_hostname'] }}
        command=undefine
        uri=qemu:///system
        state=destroyed
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]
  ignore_errors: true

- name: clean up any old disk images
  file: name={{ kvm_disk_dir }}/{{ hostvars[item]['inventory_hostname'] }}.qcow2 state=absent
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]
  ignore_errors: true

- name: Copy over the virtual disk images
  copy: src={{ guest_image }} dest={{ kvm_disk_dir }}/{{ hostvars[item]['inventory_hostname'] }}.qcow2
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: create xfs volume for gluster servers
  command: qemu-img create -f qcow2 {{ kvm_disk_dir }}/{{ hostvars[item]['inventory_hostname'] }}-gluster.qcow2 2500M
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: create temporary folder for host disk customization
  file: name={{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }} state=directory
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: create the metadata ISO directory
  file: name={{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }}/metadata state=directory
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: create meta-data files for cloud-init
  template: src=../templates/meta-data dest={{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }}/metadata/meta-data
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: create user-data files for cloud-init
  template: src=../templates/user-data dest={{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }}/metadata/user-data
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: create cloud-config ISO image
  command: genisoimage -o {{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }}-ci.iso -V cidata -r -J {{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }}/metadata/user-data {{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }}/metadata/meta-data
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: copy over cloud-init ISOs
  copy: src={{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }}-ci.iso dest={{ kvm_disk_dir }}/{{ hostvars[item]['inventory_hostname'] }}-ci.iso
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: Define guest images
  virt: name={{ hostvars[item]['inventory_hostname'] }}
        command=define
        xml="{{ lookup('template', '../templates/vm-gluster.xml') }}"
        uri=qemu:///system
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: remove any static ips from libvirt
  command: virsh net-update default delete ip-dhcp-host '<host mac="{{ hostvars[item]['mac'] }}" ip="{{ hostvars[item]['ip'] }}"/>' --config --live
  ignore_errors: true
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: add static ip addresses for the hosts
  command: virsh net-update default add ip-dhcp-host '<host mac="{{ hostvars[item]['mac'] }}" ip="{{ hostvars[item]['ip'] }}"/>' --config --live
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: stop libvirt networking
  virt_net: command=destroy name=default
  delegate_to: 127.0.0.1

- name: start libvirt networking
  virt_net: command=start name=default
  delegate_to: 127.0.0.1

- name: Start the new Virtual Machines
  virt:  name={{ hostvars[item]['inventory_hostname'] }}
         command=start
         uri=qemu:///system
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: make sure all vms are running
  local_action: wait_for host={{ hostvars[item]['inventory_hostname'] }} port=22 state=started delay=5 timeout=300
  sudo: false
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: make sure the known_hosts file exists
  file: path={{ ssh_known_hosts_file }} state=touch

- name: remove any stale entries for these virtual Machines by hostname
  shell: "ssh-keygen -R {{ hostvars[item]['inventory_hostname'] }} -f {{ ssh_known_hosts_file}}"
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: remove any stale entries for these virtual Machines by ip
  shell: "ssh-keygen -R {{ hostvars[item]['ip'] }} -f {{ ssh_known_hosts_file}}"
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: add the new ssh host keys by hostname
  shell: "ssh-keyscan {{ hostvars[item]['inventory_hostname'] }} >> {{ ssh_known_hosts_file }}"
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: add the new ssh host keys by ip
  shell: "ssh-keyscan {{ hostvars[item]['ip'] }} >> {{ ssh_known_hosts_file }}"
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"]

- name: ensure the system is accessable
  ping:
  with_items: [ "groups['gluster_guests']", "groups['atomic_guests']"] 

- name: collect the current username
  local_action: command whoami
  sudo: no
  register: local_username

- name: set the proper permissions back on known_hosts
  file: path={{ ssh_known_hosts_file }}
        owner={{ local_username.stdout }}
        group={{ local_username.stdout }}
        mode=0600
