- name: remove any old guest instances
  virt: name={{ hostvars[item]['inventory_hostname'] }}
        command=undefine
        uri=qemu:///system
        state=destroyed
  with_items: groups['packstack_guests']
  ignore_errors: true

- name: clean up any old disk images
  file: name={{ kvm_disk_dir }}/{{ hostvars[item]['inventory_hostname'] }}.qcow2 state=absent
  with_items: groups['packstack_guests']
  ignore_errors: true

- name: Copy over the virtual disk images
  copy: src={{ guest_image }} dest={{ kvm_disk_dir }}/{{ hostvars[item]['inventory_hostname'] }}.qcow2
  with_items: groups['packstack_guests']

- name: create temporary folder for host disk customization
  file: name={{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }} state=directory
  with_items: groups['packstack_guests']

#- name: create eth0 ifcfg files for each server
#  template: src=../templates/ifcfg-eth0 dest={{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }}/ifcfg-eth0
#  with_items: groups['packstack_guests']

- name: create the metadata ISO directory
  file: name={{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }}/metadata state=directory
  with_items: groups['packstack_guests']

- name: create meta-data files for cloud-init
  template: src=../templates/meta-data dest={{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }}/metadata/meta-data
  with_items: groups['packstack_guests']

- name: create user-data files for cloud-init
  template: src=../templates/user-data dest={{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }}/metadata/user-data
  with_items: groups['packstack_guests']

- name: create cloud-config ISO image
  command: genisoimage -o {{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }}-ci.iso -V cidata -r -J {{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }}/metadata/user-data {{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }}/metadata/meta-data
  with_items: groups['packstack_guests']

- name: copy over cloud-init ISOs
  copy: src={{ tmp_workspace }}/{{ hostvars[item]['inventory_hostname'] }}-ci.iso dest={{ kvm_disk_dir }}/{{ hostvars[item]['inventory_hostname'] }}-ci.iso
  with_items: groups['packstack_guests']

- name: Define guest images
  virt: name={{ hostvars[item]['inventory_hostname'] }}
        command=define
        xml="{{ lookup('template', '../templates/vm.xml') }}"
        uri=qemu:///system
  with_items: groups['packstack_guests']

- name: remove any static ips from libvirt
  command: virsh net-update default delete ip-dhcp-host '<host mac="{{ hostvars[item]['mac'] }}" ip="{{ hostvars[item]['ip'] }}"/>' --config --live
  ignore_errors: true
  with_items: groups['packstack_guests'] 

- name: add static ip addresses for the hosts
  command: virsh net-update default add ip-dhcp-host '<host mac="{{ hostvars[item]['mac'] }}" ip="{{ hostvars[item]['ip'] }}"/>' --config --live
  with_items: groups['packstack_guests']

- name: stop libvirt networking
  virt_net: command=destroy name=default
  delegate_to: 127.0.0.1

- name: start libvirt networking
  virt_net: command=start name=default
  delegate_to: 127.0.0.1
- name: Start the new Virtual Machines
  virt:  name={{ hostvars[item]['inventory_hostname'] }}
         command=start
         uri=qemu:///system
  with_items: groups['packstack_guests']

- name: make sure all vms are running
  local_action: wait_for host={{ hostvars[item]['inventory_hostname'] }} port=22 state=started delay=5 timeout=300
  sudo: false
  with_items: groups['packstack_guests']

- name: make sure the known_hosts file exists
  file: path={{ ssh_known_hosts_file }} state=touch

- name: remove any stale entries for these virtual Machines by hostname
  shell: "ssh-keygen -R {{ hostvars[item]['inventory_hostname'] }} -f {{ ssh_known_hosts_file}}"
  with_items: groups['packstack_guests']

- name: remove any stale entries for these virtual Machines by ip
  shell: "ssh-keygen -R {{ hostvars[item]['ip'] }} -f {{ ssh_known_hosts_file}}"
  with_items: groups['packstack_guests']

- name: add the new ssh host keys by hostname
  shell: "ssh-keyscan {{ hostvars[item]['inventory_hostname'] }} >> {{ ssh_known_hosts_file }}"
  with_items: groups['packstack_guests']

- name: add the new ssh host keys by ip
  shell: "ssh-keyscan {{ hostvars[item]['ip'] }} >> {{ ssh_known_hosts_file }}"
  with_items: groups['packstack_guests']

- name: ensure the system is accessable
  ping:
  with_items: groups['packstack_guests']
