kind: ReplicationController
apiVersion: v1
metadata:
  name: app-rc
  labels:
    name: app-rc
spec:
  replicas: 2
  selector:
    name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: docker.io/jeduncan/php-demo-app
        volumeMounts:
        - name: uploads
          mountPath: /opt/app-root/src/uploads
        ports:
          - name: web-port
            containerPort: 8080
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: nfs 
