apiVersion: v1
kind: Service
metadata:
  labels:
    name: app-service-nfs
  name: app-service-nfs
  namespace: default
spec:
  sessionAffinity: ClientIP
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    port: 8002
    targetPort: 8080
  selector:
    name: app-rc-nfs
  deprecatedPublicIPs:
  - {{ hostvars['kube1'].ip }}
