apiVersion: v1
kind: Service
metadata:
  labels:
    name: app-service
  name: app-service
  namespace: default
spec:
  sessionAffinity: ClientIP
  type: NodePort
  ports:
  - name: web
    protocol: TCP
    port: 8001
    targetPort: 8080
  selector:
    name: app
  deprecatedPublicIPs:
  - {{ hostvars['kube1'].ip }}
