kind: ReplicationController
apiVersion: v1
metadata:
  name: app-rc
  labels:
    name: app-rc
spec:
  replicas: 1
  selector:
    name: app
  template:
    metadata:
      labels:
        name: app
    spec:
      containers:
      - name: app
        image: docker.io/jeduncan/php-demo-app
        env:
        ports:
          - name: web-port
            containerPort: 8080
