kind: ReplicationController
apiVersion: v1
metadata:
  name: app-rc-nfs
  labels:
    name: app-rc-nfs
spec:
  replicas: 2
  selector:
    name: app-rc-nfs
  template:
    metadata:
      labels:
        name: app-rc-nfs
    spec:
      containers:
        env:
        - name: STORAGE_TYPE
          value: NFS
        - name: AUTHOR
          value: jduncan
      - name: app-rc-nfs
        image: docker.io/jeduncan/php-demo-app
        volumeMounts:
        - name: uploads
          mountPath: /opt/app-root/src/uploads
        ports:
          - name: web-port
            containerPort: 8080
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: nfs
