apiVersion: v1
kind: Service
metadata:
  labels:
    name: app-service-eph
  name: app-service-eph
  namespace: default
spec:
  sessionAffinity: ClientIP
  type: NodePort
  ports:
  - name: web-registry
    protocol: TCP
    port: 8000
    targetPort: 8080
  selector:
    name: app-eph
  deprecatedPublicIPs:
  - {{ hostvars['kube1'].ip }}
