kind: ReplicationController
apiVersion: v1
metadata:
  name: app-rc-eph
  labels:
    name: app-rc-eph
spec:
  replicas: 1
  selector:
    name: app-eph
  template:
    metadata:
      labels:
        name: app-eph
    spec:
      containers:
      - name: app-eph
        image: docker.io/jeduncan/php-demo-app:demo
        env:
        ports:
          - name: web-port
            containerPort: 8080
