apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    path: /var/registry-data
    server: 192.168.122.1
  persistentVolumeReclaimPolicy: Retain
