apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 2Gi
  nfs:
    path: {{ nfs_volume }}
    server: {{ nfs_server }}
  persistentVolumeReclaimPolicy: Retain
