# Deploys a 3-node packstack demo
# By default it makes the following assumptions:
# 1) The hypervisor is also the ansible server
# 2) It is also your laptop
# 3) your vm's are in the 'guests' group in your hosts file
# It may well work with a disconnected hypervisor but it hasn't been tested as of yet
# - jduncan

- hosts: laptop
  vars_files:
    - passes.yml
  vars:
    deploy_packstack: false
    deploy_rhevm: false
    deploy_atomic: true
  remote_user: root
  roles:
  - kvm_hypervisor

- hosts: atomic_guests
  vars:
    patch_systems: false
    provision_demo: true
    use_nfs: true
  remote_user: cloud-user
  sudo: yes
  vars_files:
    - passes.yml
  roles:
  - common
  - kvm_guests
  - atomic
  - atomic-demo
