# Atomic 3-node kubernetes with gluster storage
# - jduncan

- hosts: laptop
  vars_files:
    - passes.yml
  remote_user: root
  sudo: yes
  vars:
    deploy_packstack: false
    deploy_rhevm: false
    deploy_atomic: false
    deploy_gluster: true
  roles:
  - kvm_hypervisor

- hosts: gluster_guests
  vars:
    patch_systems: false
  sudo: yes
  remote_user: cloud-user
  vars_files:
    - passes.yml
  roles:
  - common
  - gluster
