- hosts: laptop
  vars_files:
    - passes.yml
  vars:
    group: gluster
    # The Red Hat supplied RHEL 7 image
    disk_image: "{{ rhel_disk_image }}"
  roles:
  - kvm_hypervisor

- hosts: gluster
  vars:
    patch_systems: false
  sudo: yes
  remote_user: cloud-user
  vars_files:
    - passes.yml
  roles:
  - common
  - gluster
