- hosts: laptop
  vars_files:
  - passes.yml
  vars:
    group: packstack
    # The Red Hat supplied RHEL 7 image
    disk_image: "{{ rhel_disk_image }}"
  roles:
  - kvm_hypervisor

- hosts: packstack
  vars_files:
    - passes.yml
  remote_user: cloud-user
  become: yes
  become_user: root
  roles:
  - common
  - packstack
  - packstack-demo
