- hosts: laptop
  vars_files:
  - passes.yml
  vars:
    group: packstack
    gluster: false
    # The Red Hat supplied RHEL 7 image
    disk_image: /home/jduncan/Downloads/rhel-guest-image-7.2-20160219.1.x86_64.qcow2
  remote_user: cloud-user
  sudo: yes
  roles:
  - kvm_hypervisor

- hosts: packstack_guests
  vars_files:
    - passes.yml
  remote_user: cloud-user
  become: yes
  become_user: root
  roles:
  - common
  - kvm_guests
  - packstack
  - packstack-demo
