# Deploys a 3-node packstack demo
# By default it makes the following assumptions:
# 1) The hypervisor is also the ansible server
# 2) It is also your laptop
# 3) your vm's are in the 'guests' group in your hosts file
# It may well work with a disconnected hypervisor but it hasn't been tested as of yet
# - jduncan

- hosts: laptop
  vars:
    deploy_packstack: false
    deploy_rhevm: true
    deploy_atomic: false
  remote_user: root
  roles:
  - kvm_hypervisor

- hosts: rhev_m
  remote_user: cloud-user
  vars_files:
    - passes.yml
  roles:
  - common
  - kvm_guests
  - rhev-m

- hosts: rhev_h
  remote_user: cloud-user
  roles:
  - common
  - kvm_guests
  - rhev-h
