- hosts: laptop
  vars_files:
  - passes.yml
  vars:
    group: sat62
    # The Red Hat supplied RHEL 7 image
    disk_image: "{{ rhel_disk_image }}"

  roles:
  - kvm_hypervisor

- hosts: sat62
  vars_files:
  - passes.yml

  remote_user: cloud-user
  become: yes
  become_user: root

  roles:
  - common
  - { role: satellite6, data_disk_size: '30G' }
