- name: disable all repositories so we can enable just the ones we want
  command: subscription-manager repos --disable=\*

- name: enable the needed rhel repositories
  command: subscription-manager repos --enable={{ item }}
  with_items: "{{ repo_channels }}"

- name: remove that pesky cloud-init stuff
  yum: name=cloud-init state=absent

- name: update the server
  yum: name=* state=latest

- name: install rhevm
  yum: name=rhevm state=installed

- name: reboot the system
  shell: sleep 2 && systemctl reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: wait for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay=30 timeout=300 port=22
  sudo: false

- name: create the answers file for rhevm
  template: src=../templates/rhevm_answers.txt dest=/root/rhevm_answers.txt

- name: deploy rhev-m
  command: engine-setup --config=/root/rhevm_answers.txt 
